# Generated by Django 2.2.28 on 2024-09-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("positioning", "0006_remove_beacon_mac"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beacon",
            name="name",
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
    ]
